
services:
  taxiparkbot:
    build:
      context: .
    command: python manage.py app
    volumes:
      - .:/app
    env_file:
      - .env
  
  taxiparkweb:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    