# Generated by Django 5.0.1 on 2025-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_remove_driver_car_color_remove_driver_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
