# Generated by Django 5.0.1 on 2025-03-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='tariff',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Comfort', 'Comfort'), ('Business', 'Business'), ('Premium', 'Premium')], default='Standard', max_length=10),
        ),
    ]
