# Generated by Django 5.0.1 on 2025-03-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driver_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='is_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
