# Generated by Django 5.0.1 on 2025-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kategoriya haqida')),
            ],
            options={
                'verbose_name': 'Servis kategoriya',
                'verbose_name_plural': 'Servis kategoriyalari',
            },
        ),
    ]
