# Generated by Django 5.0.1 on 2025-03-28 17:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='manager',
            managers=[
                ('active_managers', django.db.models.manager.Manager()),
            ],
        ),
    ]
