# Generated by Django 5.0.1 on 2025-03-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_rename_first_name_botuser_full_name_and_more'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='managers',
            field=models.ManyToManyField(related_name='services', to='botapp.botuser'),
        ),
    ]
