# Generated by Django 5.0.1 on 2025-03-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_manager_role'),
        ('service', '0002_service_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='managers',
            field=models.ManyToManyField(related_name='services', to='manager.manager'),
        ),
    ]
