from . import start
from . import service
from . import drivers
from . import select_service
from . import select_driver
from . import enter_summa
from . import confirm_order
from . import statistics
from . import enter_comment