# Generated by Django 5.0.1 on 2025-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_plate', models.CharField(max_length=10, unique=True)),
                ('tariff', models.CharField(choices=[('Standard', 'Standard'), ('Comfort', 'Comfort'), ('Business', 'Business'), ('Premium', 'Premium')], default='Standard', max_length=10)),
                ('balance', models.BigIntegerField(default=0)),
                ('is_deleted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
