# Generated by Django 5.0.1 on 2025-03-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='is_active',
        ),
    ]
