# Generated by Django 5.0.1 on 2025-03-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_alter_botuser_options_botuser_is_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='is_service',
        ),
        migrations.AddField(
            model_name='botuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('service', 'Service'), ('user', 'User')], default='user', max_length=15),
        ),
    ]
