# Generated by Django 5.0.1 on 2025-03-14 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_remove_botuser_is_admin_remove_botuser_is_service_and_more'),
        ('manager', '0004_manager_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='role',
        ),
        migrations.AddField(
            model_name='botuser',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='manager.manager'),
        ),
    ]
