# Generated by Django 5.0.1 on 2025-03-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='is_active',
        ),
        migrations.AddField(
            model_name='manager',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
