# Generated by Django 5.0.1 on 2025-03-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_manager_is_active_manager_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='is_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
