# Generated by Django 5.0.1 on 2025-03-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_manager_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('service', 'Service'), ('user', 'User')], default='user', max_length=15),
        ),
    ]
